In [1]:
!nvidia-smi

Tue Nov  7 15:20:01 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:04:00.0 Off |                  N/A |
| 27%   28C    P8     9W / 180W |    197MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:05:00.0 Off |                  N/A |
| 27%   29C    P8     9W / 180W |     10MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 00000000:06:00.0 Off |                  N/A |
| 27%   27C    P8     9W / 180W |     10MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 00000000:07:00.0 Off |                  N/A |
| 27%   27C    P8     9W / 180W |     10MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 1080    Off  | 00000000:0B:00.0 Off |                  N/A |
| 27%   28C    P8     9W / 180W |     10MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 1080    Off  | 00000000:0C:00.0 Off |                  N/A |
| 27%   31C    P8     9W / 180W |   7633MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 1080    Off  | 00000000:0D:00.0 Off |                  N/A |
| 27%   29C    P8     9W / 180W |   7829MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 1080    Off  | 00000000:0E:00.0 Off |                  N/A |
| 27%   25C    P8    10W / 180W |     10MiB /  8114MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

In [2]:
################################################################################
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import importlib
import numpy as np
import pandas as pd
import json
import sys
from IPython.display import display
from typing import Iterable, List, Sequence
from tracker import extractor
pd.options.display.max_columns = 0

In [3]:
################################################################################
def flatten(
        iterable: Iterable
        ) -> Iterable:
    """
    Return a flattened iterable from a nested iterable.
    [[3, [4, 5]], 6, [[[7]]]] -> [3, 4, 5, 6, 7]
    
    Arguments:
        iterable
            Some Iterable object that may or may not contain more Iterable
            objects.
            
    Yields the elements from each Iterable or single element from iterable.
    """
    for item in iterable:
        if  isinstance(item, Iterable) and not isinstance(item, (str, bytes)):
            yield from flatten(item)
        else:
            yield item


def parse_file(
        filename         : str,
        initial_event_id : int      = 0,
        ignored_columns  : Sequence = (),
        ) -> Iterable[Iterable]:
    """ 
    Parses the lines in the file from 'filename' to a format
    appropriate for passing into a pandas DataFrame constructor.
        
    Arguments:
        filename
            The name of the file to parse.
        initial_event_id
            The event ID that the first event extracted has.
            Event ID is incremented by 1 after finishing the
            parsing of an event.
        ignored_columns
            The list of indices of the columns to delete from each line.
    
    For each line, yields a generator that yield the elements from the line.
    """
    event_id = initial_event_id
    with open(filename) as file:
        lines = filter(None, (line.strip() for line in file))
        for line in lines:
            if line.startswith("#"):
                event_id += 1
            else:
                j_list = json.loads("[{0}]".format(line))
                for column in ignored_columns:
                    del j_list[column]
                j_list.append(event_id)
                yield flatten(j_list)

In [4]:
################################################################################
clusters_columns = [
    "hit_nr", "barcode", "volume_id", "layer_id",
    "lx",     "ly",      "elx",       "ely",    
    "gx",     "gy",      "gz",        "phi",    
    "theta",  "ephi",    "etheta",    "event_id",
]
particles_columns = [
    "barcode",  "vertex_x", "vertex_y",
    "vertex_z", "momentum", "theta",
    "phi",      "charge",   "event_id",
]

# Extraction from a single file.

In [5]:
################################################################################
number = 1
base_directory     = "/inputdata/ACTS/prod_mu200_pt500_2017_07_26"
clusters_filename  = base_directory + "/clusters_{0}.csv".format(number)
particles_filename = base_directory + "/particles_{0}.csv".format(number)

In [6]:
################################################################################
# Example of how the file looks.
with open(clusters_filename, "r") as file:
    for _ in range(5):
        print(file.readline())

### Format hit_nr, barcode, volume_id, layer_id , [lx, ly], [elx, ely], [ gx, gy, gz ],[[fch0,fch1,fchdata]], [phi,theta], [ephi,etheta]

1, 752102443440930816, 7, 2, [ 0.625, 28.0611], [ 0.15, 0.15],[ -166.363, -23.8377,-1498], [[ 180, 1138, 0.144688], [ 180, 1139, 0.0828125]], [ -3.00299, 1.5708], [ 0.1, 0.01]

2, 58548238264827904, 7, 2, [ -2.575, 14.1469], [ 0.15, 0.15],[ -146.974, -46.545,-1498], [[ 116, 891, 0.268438]], [ -2.8349, 3.03904], [ 0.1, 0.01]

3, 477381629220749312, 7, 2, [ -1.225, 13.6928], [ 0.15, 0.15],[ -146.115, -47.6808,-1498], [[ 143, 882, 0.0209375], [ 143, 883, 0.268438]], [ -2.81819, 1.5708], [ 0.1, 0.01]

In [7]:
################################################################################
# Quick note: I am ignoring the 7th column within each line.
# This column contains [[fch0, fch1, fchdata]]. 
clusters_lines = parse_file(clusters_filename, ignored_columns=[7])
clusters_frame = pd.DataFrame(clusters_lines, columns=clusters_columns)
clusters_frame.head(6)

   hit_nr             barcode  volume_id    ...     ephi  etheta  event_id
0       1  752102443440930816          7    ...      0.1    0.01         1
1       2   58548238264827904          7    ...      0.1    0.01         1
2       3  477381629220749312          7    ...      0.1    0.01         1
3       4  414331990351806464          7    ...      0.1    0.01         1
4       5  756604874837196800          7    ...      0.1    0.01         1
5       6  405336335969157120          7    ...      0.1    0.01         1

[6 rows x 16 columns]

In [8]:
################################################################################
clusters_frame = clusters_frame.rename(columns={
    "hit_nr": "hit_number", "barcode": "cluster_id", "lx": "local_x",
    "ly": "local_y", "gx": "x", "gy": "y", "gz": "z", "elx": "local_x_error",
    "ely": "local_y_error", "ephi": "phi_error", "etheta": "theta_error"
})
clusters_frame.head(6)

   hit_number          cluster_id    ...     theta_error  event_id
0           1  752102443440930816    ...            0.01         1
1           2   58548238264827904    ...            0.01         1
2           3  477381629220749312    ...            0.01         1
3           4  414331990351806464    ...            0.01         1
4           5  756604874837196800    ...            0.01         1
5           6  405336335969157120    ...            0.01         1

[6 rows x 16 columns]

In [9]:
################################################################################
events = clusters_frame.groupby(["event_id"])["cluster_id"]
tracks_per_event = [len(event.unique()) for (_, event) in events]

print("Hits:", len(clusters_frame))
print("Events:", len(clusters_frame["event_id"].unique()))
print("Min Tracks:", min(tracks_per_event))
print("Max Tracks:", max(tracks_per_event))

Hits: 3029037
Events: 100
Min Tracks: 1732
Max Tracks: 3252

In [10]:
################################################################################
particles_lines = parse_file(particles_filename)
particles_frame = pd.DataFrame(particles_lines, columns=particles_columns)
particles_frame.head(6)

            barcode  vertex_x  vertex_y    ...          phi  charge  event_id
0       68719476736  0.022137  0.006326    ...     1.253420      -1         1
1      824633720832  0.022137  0.006326    ...     2.614390      -1         1
2  4503874505277440 -0.010566 -0.011323    ...    -2.226300       1         1
3  4503943224754176 -0.010566 -0.011323    ...    -0.783333      -1         1
4  4504080663707648 -0.010566 -0.011323    ...    -0.390961      -1         1
5  4504561700044800 -0.010566 -0.011323    ...     2.293790      -1         1

[6 rows x 9 columns]

In [11]:
################################################################################
particles_frame = particles_frame.rename(columns={
    "barcode": "cluster_id", "theta": "momentum_theta", "phi": "momentum_phi"
})
particles_frame.head(6)

         cluster_id  vertex_x  vertex_y    ...     momentum_phi  charge  event_id
0       68719476736  0.022137  0.006326    ...         1.253420      -1         1
1      824633720832  0.022137  0.006326    ...         2.614390      -1         1
2  4503874505277440 -0.010566 -0.011323    ...        -2.226300       1         1
3  4503943224754176 -0.010566 -0.011323    ...        -0.783333      -1         1
4  4504080663707648 -0.010566 -0.011323    ...        -0.390961      -1         1
5  4504561700044800 -0.010566 -0.011323    ...         2.293790      -1         1

[6 rows x 9 columns]

In [12]:
################################################################################
events = particles_frame.groupby(["event_id"])["cluster_id"]
tracks_per_event = [len(event.unique()) for (_, event) in events]

print("Hits:", len(particles_frame))
print("Events:", len(particles_frame["event_id"].unique()))
print("Min Tracks:", min(tracks_per_event))
print("Max Tracks:", max(tracks_per_event))

Hits: 248386
Events: 100
Min Tracks: 1732
Max Tracks: 3252

In [13]:
################################################################################
combined_frame = clusters_frame.merge(
    particles_frame,
    on=["event_id", "cluster_id"])
combined_frame.head(6)

   hit_number          cluster_id   ...    momentum_phi  charge
0           1  752102443440930816   ...        -3.02523      -1
1          61  752102443440930816   ...        -3.02523      -1
2         298  752102443440930816   ...        -3.02523      -1
3         597  752102443440930816   ...        -3.02523      -1
4         937  752102443440930816   ...        -3.02523      -1
5         954  752102443440930816   ...        -3.02523      -1

[6 rows x 23 columns]

In [14]:
################################################################################
x     = combined_frame["x"]
y     = combined_frame["y"]
frame = combined_frame.assign(r=np.sqrt(x**2 + y**2), phi=np.arctan2(y, x))
frame.head(6)

   hit_number          cluster_id     ...      charge           r
0           1  752102443440930816     ...          -1  168.062142
1          61  752102443440930816     ...          -1  121.128599
2         298  752102443440930816     ...          -1  104.704580
3         597  752102443440930816     ...          -1   88.814788
4         937  752102443440930816     ...          -1   74.727233
5         954  752102443440930816     ...          -1   74.204364

[6 rows x 24 columns]

In [15]:
################################################################################
# Eliminate duplicate hits that were caused by imperfections in the detector.
frame = frame.sort_values("r")
frame = frame.drop_duplicates(["event_id", "cluster_id", "layer_id"])

In [16]:
################################################################################
# Specify the volume to use. Each volume is a different detector configuration.
frame = frame[frame["volume_id"] == 8]

In [17]:
################################################################################
# Set radiuses to be the same for each layer.
for layer_id in frame["layer_id"].unique():
    ind = frame["layer_id"] == layer_id
    rs  = frame[ind]["r"]
    med = rs.median()
    frame.loc[ind, "r"] = med

In [18]:
################################################################################
# Clean up the frame a bit.
frame = frame.sort_values(["event_id", "cluster_id", "r"])
frame.head(6)

       hit_number    cluster_id     ...      charge           r
11000        3018   68719476736     ...          -1   31.959887
11001        5601   68719476736     ...          -1   71.842084
11002        7429   68719476736     ...          -1  115.820577
11003        9198   68719476736     ...          -1  171.805748
17628        3754  824633720832     ...          -1   31.959887
17629        6006  824633720832     ...          -1   71.842084

[6 rows x 24 columns]

In [19]:
################################################################################
events = frame.groupby(["event_id"])["cluster_id"]
tracks_per_event = [len(event.unique()) for (_, event) in events]

print("Hits:", len(frame))
print("Events:", len(frame["event_id"].unique()))
print("Min Tracks:", min(tracks_per_event))
print("Max Tracks:", max(tracks_per_event))

Hits: 795033
Events: 100
Min Tracks: 1731
Max Tracks: 3249

# Extraction from multiple files.

In [20]:
################################################################################
def get_clusters_frame(
        clusters_filename : str,
        initial_event_id  : int,
        ) -> pd.DataFrame:
    clusters_lines = parse_file(
        clusters_filename,
        ignored_columns=[7],
        initial_event_id=initial_event_id)
    clusters_frame = pd.DataFrame(clusters_lines, columns=clusters_columns)
    clusters_frame = clusters_frame.rename(columns={
        "hit_nr": "hit_number", "barcode": "cluster_id", "lx": "local_x",
        "ly": "local_y", "gx": "x", "gy": "y", "gz": "z", "elx":
        "local_x_error", "ely": "local_y_error", "ephi": "phi_error",
        "etheta": "theta_error"})
    return clusters_frame

def get_particles_frame(
        particles_filename : str,
        initial_event_id   : int,
        ) -> pd.DataFrame:
    particles_lines = parse_file(
        particles_filename, 
        initial_event_id=initial_event_id)
    particles_frame = pd.DataFrame(particles_lines, columns=particles_columns)
    particles_frame = particles_frame.rename(columns={
        "barcode": "cluster_id", "theta": "momentum_theta",
        "phi": "momentum_phi"})
    return particles_frame

def extract(
        clusters_filename  : str, 
        particles_filename : str,
        volume_id          : int = 8,
        initial_event_id   : int = 0,
        ) -> pd.DataFrame:
    """
    Everything in one function.
    Depending on the size of the file, this function could take a long
    time. Most of the time is spent parsing the csv files within the
    first 4 lines.
    """
    clusters  = get_clusters_frame(clusters_filename, initial_event_id)
    particles = get_particles_frame(particles_filename, initial_event_id)
    combined  = clusters.merge(particles, on=["event_id", "cluster_id"])
    volume    = combined[combined["volume_id"] == volume_id]
    x, y      = volume["x"], volume["y"]
    
    return (
        volume.assign(r=np.sqrt(x**2 + y**2))
              .assign(phi=np.arctan2(y, x))
              .sort_values(["event_id", "cluster_id", "r"])
              .drop_duplicates(["event_id", "cluster_id", "layer_id"])
    )

In [21]:
%%time
################################################################################
frames = []
initial_event_id = 0
base_directory = "/inputdata/ACTS/prod_mu10_pt1000_2017_07_29"
for i in range(1, 1 + 100):
    print("Extracting from file {0}. Initial Event ID is {1}".format(i, initial_event_id))
    try:
        clusters_filename  = base_directory + "/clusters_{0}.csv".format(i)
        particles_filename = base_directory + "/particles_{0}.csv".format(i)
        frame = extract(
            clusters_filename=clusters_filename, 
            particles_filename=particles_filename,
            initial_event_id=initial_event_id,)
        initial_event_id = frame["event_id"].max() + 1
        frames.append(frame)
    except FileNotFoundError as error:
        print(error)
print("All done. Concatenating frames.")
frame = pd.concat(frames)
for layer_id in frame["layer_id"].unique():
    ind = frame["layer_id"] == layer_id
    rs  = frame[ind]["r"]
    med = rs.median()
    frame.loc[ind, "r"] = med

Extracting from file 1. Initial Event ID is 0
Extracting from file 2. Initial Event ID is 1001
Extracting from file 3. Initial Event ID is 2002
Extracting from file 4. Initial Event ID is 3003
Extracting from file 5. Initial Event ID is 4004
Extracting from file 6. Initial Event ID is 5005
Extracting from file 7. Initial Event ID is 6006
Extracting from file 8. Initial Event ID is 7007
Extracting from file 9. Initial Event ID is 8008
Extracting from file 10. Initial Event ID is 9009
Extracting from file 11. Initial Event ID is 10010
Extracting from file 12. Initial Event ID is 11011
Extracting from file 13. Initial Event ID is 12012
Extracting from file 14. Initial Event ID is 13013
Extracting from file 15. Initial Event ID is 14014
Extracting from file 16. Initial Event ID is 15015
Extracting from file 17. Initial Event ID is 16016
Extracting from file 18. Initial Event ID is 17017
Extracting from file 19. Initial Event ID is 18018
Extracting from file 20. Initial Event ID is 19019
Extracting from file 21. Initial Event ID is 20020
Extracting from file 22. Initial Event ID is 21021
Extracting from file 23. Initial Event ID is 22022
Extracting from file 24. Initial Event ID is 23023
Extracting from file 25. Initial Event ID is 24024
Extracting from file 26. Initial Event ID is 25025
Extracting from file 27. Initial Event ID is 26026
Extracting from file 28. Initial Event ID is 27027
Extracting from file 29. Initial Event ID is 28028
Extracting from file 30. Initial Event ID is 29029
Extracting from file 31. Initial Event ID is 30030
Extracting from file 32. Initial Event ID is 31031
Extracting from file 33. Initial Event ID is 32032
Extracting from file 34. Initial Event ID is 33033
Extracting from file 35. Initial Event ID is 34034
Extracting from file 36. Initial Event ID is 35035
Extracting from file 37. Initial Event ID is 36036
Extracting from file 38. Initial Event ID is 37037
Extracting from file 39. Initial Event ID is 38038
Extracting from file 40. Initial Event ID is 39039
Extracting from file 41. Initial Event ID is 40040
Extracting from file 42. Initial Event ID is 41041
Extracting from file 43. Initial Event ID is 42042
Extracting from file 44. Initial Event ID is 43043
Extracting from file 45. Initial Event ID is 44044
Extracting from file 46. Initial Event ID is 45045
Extracting from file 47. Initial Event ID is 46046
Extracting from file 48. Initial Event ID is 47047
Extracting from file 49. Initial Event ID is 48048
Extracting from file 50. Initial Event ID is 49049
Extracting from file 51. Initial Event ID is 50050
Extracting from file 52. Initial Event ID is 51051
Extracting from file 53. Initial Event ID is 52052
Extracting from file 54. Initial Event ID is 53053
Extracting from file 55. Initial Event ID is 54054
Extracting from file 56. Initial Event ID is 55055
Extracting from file 57. Initial Event ID is 56056
Extracting from file 58. Initial Event ID is 57057
Extracting from file 59. Initial Event ID is 58058
Extracting from file 60. Initial Event ID is 59059
Extracting from file 61. Initial Event ID is 60060
Extracting from file 62. Initial Event ID is 61061
Extracting from file 63. Initial Event ID is 62062
Extracting from file 64. Initial Event ID is 63063
Extracting from file 65. Initial Event ID is 64064
Extracting from file 66. Initial Event ID is 65065
Extracting from file 67. Initial Event ID is 66066
Extracting from file 68. Initial Event ID is 67067
Extracting from file 69. Initial Event ID is 68068
Extracting from file 70. Initial Event ID is 69069
Extracting from file 71. Initial Event ID is 70070
Extracting from file 72. Initial Event ID is 71071
Extracting from file 73. Initial Event ID is 72072
Extracting from file 74. Initial Event ID is 73073
Extracting from file 75. Initial Event ID is 74074
Extracting from file 76. Initial Event ID is 75075
Extracting from file 77. Initial Event ID is 76076
Extracting from file 78. Initial Event ID is 77077
Extracting from file 79. Initial Event ID is 78078
Extracting from file 80. Initial Event ID is 79079
Extracting from file 81. Initial Event ID is 80080
Extracting from file 82. Initial Event ID is 81081
Extracting from file 83. Initial Event ID is 82082
Extracting from file 84. Initial Event ID is 83083
Extracting from file 85. Initial Event ID is 84084
Extracting from file 86. Initial Event ID is 85085
Extracting from file 87. Initial Event ID is 86086
Extracting from file 88. Initial Event ID is 87087
Extracting from file 89. Initial Event ID is 88088
Extracting from file 90. Initial Event ID is 89089
Extracting from file 91. Initial Event ID is 90090
Extracting from file 92. Initial Event ID is 91091
Extracting from file 93. Initial Event ID is 92092
Extracting from file 94. Initial Event ID is 93093
Extracting from file 95. Initial Event ID is 94094
Extracting from file 96. Initial Event ID is 95095
Extracting from file 97. Initial Event ID is 96096
Extracting from file 98. Initial Event ID is 97097
Extracting from file 99. Initial Event ID is 98098
Extracting from file 100. Initial Event ID is 99099
All done. Concatenating frames.
CPU times: user 1h 35min 26s, sys: 2min 9s, total: 1h 37min 36s
Wall time: 1h 37min 39s

In [22]:
%%time
################################################################################
print("Number of Hits: {}".format(len(frame)))
print("Number of Events: {}".format(len(frame["event_id"].unique())))
tracks  = [value for (_, value) in frame.groupby(["event_id"])]
lengths = [len(value["cluster_id"].unique()) for value in tracks]
print("Min Number of Tracks: {}".format(min(lengths)))
print("Max Number of Tracks: {}".format(max(lengths)))

Number of Hits: 13929190
Number of Events: 99615
Min Number of Tracks: 1
Max Number of Tracks: 246
CPU times: user 27.8 s, sys: 16.9 s, total: 44.7 s
Wall time: 44.6 s

In [23]:
%%time
################################################################################
savepath = "data/sets/ACTS-MU10-PT1000-COMPLETE.gz"
frame.to_csv(savepath, compression="gzip")

CPU times: user 12min 50s, sys: 532 ms, total: 12min 50s
Wall time: 12min 50s

# Preparing the extracted frame.

In [24]:
%%time
################################################################################
max_tracks = 50
max_len    = lambda event: len(event["cluster_id"].unique()) <= max_tracks
filtered   = frame.groupby("event_id").filter(max_len)

CPU times: user 34.8 s, sys: 45 s, total: 1min 19s
Wall time: 1min 19s

In [28]:
print(len(filtered["event_id"].unique()))
print(len(frame["event_id"].unique()))

65407
99615

In [29]:
%%time
################################################################################
prepared = extractor.prepare_frame(
    frame    = filtered,
    n_tracks = max_tracks,
    n_rows   = 200,
    n_noise  = 0,
)
prepared = prepared.sort_values(["event_id", "cluster_id", "r"])

CPU times: user 12min 17s, sys: 29.5 s, total: 12min 46s
Wall time: 12min 46s

In [30]:
%%time
################################################################################
savepath = "data/sets/ACTS-MU10-PT1000-PREPARED.gz"
prepared.to_csv(savepath, compression="gzip")

CPU times: user 9min 55s, sys: 296 ms, total: 9min 55s
Wall time: 9min 55s